export const CATEGORIES = [
  "Cleaning",
  "Repair",
  "Delivery",
  "Tech",
  "Car Service",
  "Household Help",
  "Electrical Work",
  "Plumbing",
  "Gardening",
  "Moving & Shifting",
  "Computer Help",
  "Painting",
  "Vehicle Help",
  "Event Assistance",
  "Shopping Assistance",
  "Elderly Care",
  "Other",
];
